[package]
name = "sample"
version = "0.1.0"
edition = "2024"
license = "MIT"
keywords = ["wgpu", "rust-windowing", "graphics", "winit"]
description = "Example to illustrate - a starter package to get started with wgpu library"
repository = "https://github.com/opal-ui/wgpu-starter-rs"
publish = false

[dependencies]
wgpu_quick_start = { path="../lib", features = ["enable-sync-winit"] }
winit_app = {version="0.31"}
wgpu = { version = "28", default-features = false, features = ["wgsl", "vulkan", "dx12", "metal", "gles"] }
winit = { version = "0.31.0-beta.2", features = ["android-native-activity"] }
log = "0.4"
simple_logger="5"

