[package]
name = "wgpu_quick_start"
version = "0.28.5"
edition = "2024"
license = "MIT"
keywords = ["wgpu", "rust-windowing", "graphics", "winit"]
description = "A starter package to get started with wgpu library"
repository = "https://github.com/opal-ui/wgpu-quick-start-rs"
readme = "README.md"
homepage = "https://opal-ui.github.io/wgpu-quick-start-rs/"


[lib]
name="wgpu_quick_start"

[features]
sync=["dep:pollster", "dep:winit"]

[dependencies]
wgpu = { version = "28", default-features = false, features = ["wgsl", "vulkan", "dx12", "metal", "gles"] }
thiserror = "2.0.17"
log="0.4"
pollster = {version ="0.4.0" , optional=true}
winit = { version = "0.31.0-beta.2", optional=true, features = ["android-native-activity"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.6"
console_log = "1.0"
wgpu = { version = "28", features = ["webgl"]}
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.30"
web-sys = { version = "0.3", features = [
    "Document",
    "Window",
    "Element",
]}
 

[dev-dependencies]
winit_app = {version="0.31.0"}
