name: CI Pipeline
run-name: ${{ github.actor }} is using Github Actions to check code

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable # A popular action for setting up the Rust environment

      - name: Run cargo build
        working-directory: ./lib
        run: cargo build --all-features --verbose

      - name: Run cargo test
        working-directory: ./lib
        run: cargo test --all-features --verbose        

      - name: Run cargo doc
        working-directory: ./lib
        run: cargo d --no-deps --all-features

      - name: Run a script
        run: echo "Add your build and test commands here"
